/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ServerConfigRepresentation } from '../model/serverConfigRepresentation';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ServerConfigsResourceService {

    protected basePath = 'https://localhost:8081';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getDefaultServerConfig
     *
     * @param endpointTypeCode endpointTypeCode
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDefaultServerConfig(endpointTypeCode: number, observe?: 'body', reportProgress?: boolean): Observable<ServerConfigRepresentation>;
    public getDefaultServerConfig(endpointTypeCode: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ServerConfigRepresentation>>;
    public getDefaultServerConfig(endpointTypeCode: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ServerConfigRepresentation>>;
    public getDefaultServerConfig(endpointTypeCode: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (endpointTypeCode === null || endpointTypeCode === undefined) {
            throw new Error('Required parameter endpointTypeCode was null or undefined when calling getDefaultServerConfig.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ServerConfigRepresentation>(`${this.basePath}/rest/server-configs/default/${encodeURIComponent(String(endpointTypeCode))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getServers
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getServers(observe?: 'body', reportProgress?: boolean): Observable<Array<ServerConfigRepresentation>>;
    public getServers(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ServerConfigRepresentation>>>;
    public getServers(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ServerConfigRepresentation>>>;
    public getServers(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<ServerConfigRepresentation>>(`${this.basePath}/rest/server-configs`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateServer
     *
     * @param serverId serverId
     * @param configRepresentation configRepresentation
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateServer(serverId: string, configRepresentation: ServerConfigRepresentation, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateServer(serverId: string, configRepresentation: ServerConfigRepresentation, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateServer(serverId: string, configRepresentation: ServerConfigRepresentation, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateServer(serverId: string, configRepresentation: ServerConfigRepresentation, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (serverId === null || serverId === undefined) {
            throw new Error('Required parameter serverId was null or undefined when calling updateServer.');
        }

        if (configRepresentation === null || configRepresentation === undefined) {
            throw new Error('Required parameter configRepresentation was null or undefined when calling updateServer.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/rest/server-configs/${encodeURIComponent(String(serverId))}`,
            configRepresentation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
