/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CompleteFormRepresentation } from '../model/completeFormRepresentation';
import { FormModelRepresentation } from '../model/formModelRepresentation';
import { SaveFormRepresentation } from '../model/saveFormRepresentation';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TaskFormResourceService {

    protected basePath = 'https://localhost:8081';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * completeTaskForm
     *
     * @param taskId taskId
     * @param completeTaskFormRepresentation completeTaskFormRepresentation
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public completeTaskForm(taskId: string, completeTaskFormRepresentation: CompleteFormRepresentation, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public completeTaskForm(taskId: string, completeTaskFormRepresentation: CompleteFormRepresentation, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public completeTaskForm(taskId: string, completeTaskFormRepresentation: CompleteFormRepresentation, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public completeTaskForm(taskId: string, completeTaskFormRepresentation: CompleteFormRepresentation, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling completeTaskForm.');
        }

        if (completeTaskFormRepresentation === null || completeTaskFormRepresentation === undefined) {
            throw new Error('Required parameter completeTaskFormRepresentation was null or undefined when calling completeTaskForm.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/app/rest/task-forms/${encodeURIComponent(String(taskId))}`,
            completeTaskFormRepresentation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getTaskForm
     *
     * @param taskId taskId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTaskForm(taskId: string, observe?: 'body', reportProgress?: boolean): Observable<FormModelRepresentation>;
    public getTaskForm(taskId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FormModelRepresentation>>;
    public getTaskForm(taskId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FormModelRepresentation>>;
    public getTaskForm(taskId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling getTaskForm.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<FormModelRepresentation>(`${this.basePath}/app/rest/task-forms/${encodeURIComponent(String(taskId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saveTaskForm
     *
     * @param taskId taskId
     * @param saveFormRepresentation saveFormRepresentation
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveTaskForm(taskId: string, saveFormRepresentation: SaveFormRepresentation, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public saveTaskForm(taskId: string, saveFormRepresentation: SaveFormRepresentation, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public saveTaskForm(taskId: string, saveFormRepresentation: SaveFormRepresentation, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public saveTaskForm(taskId: string, saveFormRepresentation: SaveFormRepresentation, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling saveTaskForm.');
        }

        if (saveFormRepresentation === null || saveFormRepresentation === undefined) {
            throw new Error('Required parameter saveFormRepresentation was null or undefined when calling saveTaskForm.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/app/rest/task-forms/${encodeURIComponent(String(taskId))}/save-form`,
            saveFormRepresentation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
