/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AppDefinitionRepresentation { 
    appDefinitionId?: string;
    appDefinitionKey?: string;
    defaultAppId?: string;
    description?: string;
    groupsAccess?: Array<string>;
    icon?: string;
    name?: string;
    tenantId?: string;
    theme?: string;
    usersAccess?: Array<string>;
}
