/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RestVariable } from './restVariable';
import { UserRepresentation } from './userRepresentation';


export interface CaseInstanceRepresentation { 
    businessKey?: string;
    caseDefinitionCategory?: string;
    caseDefinitionDeploymentId?: string;
    caseDefinitionDescription?: string;
    caseDefinitionId?: string;
    caseDefinitionKey?: string;
    caseDefinitionName?: string;
    caseDefinitionVersion?: number;
    ended?: Date;
    graphicalNotationDefined?: boolean;
    id?: string;
    name?: string;
    startFormDefined?: boolean;
    started?: Date;
    startedBy?: UserRepresentation;
    tenantId?: string;
    variables?: Array<RestVariable>;
}
