/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LayoutDefinition } from './layoutDefinition';


export interface FormField { 
    id?: string;
    layout?: LayoutDefinition;
    name?: string;
    overrideId?: boolean;
    params?: any;
    placeholder?: string;
    readOnly?: boolean;
    required?: boolean;
    type?: string;
    value?: any;
}
