/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FormField } from './formField';
import { FormOutcome } from './formOutcome';


export interface FormModelRepresentation { 
    description?: string;
    fields?: Array<FormField>;
    id?: string;
    key?: string;
    name?: string;
    outcomeVariableName?: string;
    outcomes?: Array<FormOutcome>;
    version?: number;
}
