/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupRepresentation } from './groupRepresentation';
import { UserRepresentation } from './userRepresentation';


export interface PrivilegeRepresentation { 
    groups?: Array<GroupRepresentation>;
    id?: string;
    name?: string;
    users?: Array<UserRepresentation>;
}
