/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ServerConfigRepresentation { 
    contextRoot?: string;
    description?: string;
    endpointType?: number;
    id?: string;
    name?: string;
    password?: string;
    restRoot?: string;
    serverAddress?: string;
    serverPort?: number;
    userName?: string;
}
