/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupRepresentation } from './groupRepresentation';


export interface UserRepresentation { 
    email?: string;
    firstName?: string;
    fullName?: string;
    groups?: Array<GroupRepresentation>;
    id?: string;
    lastName?: string;
    privileges?: Array<string>;
    tenantId?: string;
}
